<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert(['name'=>'Squash Racquets Pickle Ball Paddle Set Juciao Graphite Composite 3K Twill Carbon Fiber Surface Usapa Approved Outdoor Sports','price'=>131.16,'sku'=>'887382002','type'=>'Paddles','tags'=>'Squash,Racquets,Pickle,Ball,Paddle,Set,Juciao,Graphite,Composite,3K,Twill,Carbon,Fiber,Surface,Usapa,Approved,Outdoor,Sports,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/squash-racquets-pickle-ball-paddle-set-juciao/887382002.html?d1_page_num=1&dspm=pcen.sp.list.25.bCOwVldPCoZyAhpDwZsN&resource_id=887382002&scm_id=search.LIST..@.prerank001|3|0|unrerank|7_0|ER-B|newes|7_0.newC.#s1-24-1;searl|3686327508:25','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Tennis Rackets Portable Pickleball Paddle Set Includes 2 Rackets 4 Balls Pickleball Lightweight for Outdoor Sports Composite Adults Men Women','price'=>153.75,'sku'=>'898020718','type'=>'Paddles','tags'=>'Tennis,Rackets,Portable,Pickleball,Paddle,Set,Includes,2,Rackets,4,Balls,Pickleball,Lightweight,for,Outdoor,Sports,Composite,Adults,Men,Women,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/tennis-rackets-portable-pickleball-paddle/898020718.html?d1_page_num=1&dspm=pcen.sp.list.29.bCOwVldPCoZyAhpDwZsN&resource_id=898020718&scm_id=search.LIST..@.prerank001|3|0|unrerank|7_0|ER-B|newes|7_0.newC.&skuid=1156884084873191449#s1-28-1;searl|3686327508:29','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Squash Racquets AMASPORT Pickleball Paddles for Beginner Rough Face Polymer Honeycomb Core TPE Edge Gurad Multiple Color Pickleball Padel','price'=>81.86,'sku'=>'900289861','type'=>'Paddles','tags'=>'Squash,Racquets,AMASPORT,Pickleball,Paddles,for,Beginner,Rough,Face,Polymer,Honeycomb,Core,TPE,Edge,Gurad,Multiple,Color,Pickleball,Padel,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/squash-racquets-amasport-pickleball-paddles/900289861.html?dspm=pcen.pd.moreitem.6.eTJw976EChTLHf084Ufg&resource_id=900289861&scm_id=search.pdmoreitem..@.1|2|0|unrerank|newes..&skuid=1160168843800559637#pdmoreitem-6-5|null::r2472217853','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Tennis Rackets Pickleball Paddle Graphite Pickleball Racket With Polymer Honeycomb Composite Core Ultra Cushion 4.25In Grip Edge Bundle','price'=>107.25,'sku'=>'884339184','type'=>'Paddles','tags'=>'Tennis,Rackets,Pickleball,Paddle,Graphite,Pickleball,Racket,With,Polymer,Honeycomb,Composite,Core,Ultra,Cushion,4.25In,Grip,Edge,Bundle,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/tennis-rackets-pickleball-paddle-graphite/884339184.html?d1_page_num=1&dspm=pcen.sp.list.6.bCOwVldPCoZyAhpDwZsN&resource_id=884339184&scm_id=search.LIST..@.prerank001|3|0|unrerank|7_0|ER-B|newes|7_0.newC.&skuid=1139711265017774109#s1-5-1;searl|3686327508:6','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Tennis Rackets Pickleball Paddle Graphite Pickleball Racket with Carbon Fiber Surface and Polymer Honeycomb Composite Core for Outdoor Indoor','price'=>107.19,'sku'=>'884339084','type'=>'Paddles','tags'=>'Tennis,Rackets,Pickleball,Paddle,Graphite,Pickleball,Racket,with,Carbon,Fiber,Surface,and,Polymer,Honeycomb,Composite,Core,for,Outdoor,Indoor,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/tennis-rackets-pickleball-paddle-graphite/884339084.html?d1_page_num=1&dspm=pcen.sp.list.5.bCOwVldPCoZyAhpDwZsN&resource_id=884339084&scm_id=search.LIST..@.prerank001|3|0|unrerank|7_0|ER-B|newes|7_0.newC.#s1-4-1;searl|3686327508:5','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Tennis Rackets Juciao Selling Pickleball Paddle High Quality Full Carbon Fiber Composite','price'=>86.18,'sku'=>'840685614','type'=>'Paddles','tags'=>'Tennis,Rackets,Juciao,Selling,Pickleball,Paddle,High,Quality,Full,Carbon,Fiber,Composite,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/tennis-rackets-juciao-selling-pickleball/840685614.html?d1_page_num=1&dspm=pcen.sp.list.1.bCOwVldPCoZyAhpDwZsN&resource_id=840685614&scm_id=search.LIST..@.prerank001|3|0|unrerank|7_0|ER-B|newes|7_0.newC.&skuid=1084692711539503104#s1-0-1;searl|3686327508:1','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Squash Racquets High Quality Juciao Pickleball Paddle Selling Graphite Composite Carbon Pickleball Racket','price'=>109.47,'sku'=>'898532553','type'=>'Paddles','tags'=>'Squash,Racquets,High,Quality,Juciao,Pickleball,Paddle,Selling,Graphite,Composite,Carbon,Pickleball,Racket,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/squash-racquets-high-quality-juciao-pickleball/898532553.html?d1_page_num=1&dspm=pcen.sp.list.14.7nHAGMgpTnwIbPEbZl89&resource_id=898532553&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.&skuid=1157809318455488529#s1-13-1;searl|1493795959:14','delivery'=>22]);
        DB::table('products')->insert(['name'=>'CAMEWIN Brand Pickleball Paddle | Set Includes One Pickleball Paddles + Two Balls + One Carrying Bag | Racket Sets','price'=>96.20,'sku'=>'411823969','type'=>'Paddles','tags'=>'CAMEWIN,Brand,Pickleball,Paddle,|,Set,Includes,One,Pickleball,Paddles,+,Two,Balls,+,One,Carrying,Bag,|,Racket,Sets,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/camewin-brand-pickleball-paddle-set-includes/411823969.html?d1_page_num=1&dspm=pcen.sp.list.2.uQQD1pxO83xuKmCIH5t5&resource_id=411823969&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-1-1;searl|3159699503:2','delivery'=>15]);
        DB::table('products')->insert(['name'=>'Tennis Rackets Pickleball Paddles Set with 1/2/4 Premium Wood Pickleball Paddles 4 Pickleball Balls 2/4 Cooling Towels Carry Bag','price'=>153.80,'sku'=>'898020668','type'=>'Paddles','tags'=>'Tennis,Rackets,Pickleball,Paddles,Set,with,1/2/4,Premium,Wood,Pickleball,Paddles,4,Pickleball,Balls,2/4,Cooling,Towels,Carry,Bag,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/tennis-rackets-pickleball-paddles-set-with/898020668.html?d1_page_num=1&dspm=pcen.sp.list.6.uQQD1pxO83xuKmCIH5t5&resource_id=898020668&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-5-1;searl|3159699503:6','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Squash Racquets Pickleball Paddles Set Rackets Wood with 4 Balls Carry Bag for Adults Women Pickleball Rackets Outdoor Training Sports','price'=>75.18,'sku'=>'899913565','type'=>'Paddles','tags'=>'Squash,Racquets,Pickleball,Paddles,Set,Rackets,Wood,with,4,Balls,Carry,Bag,for,Adults,Women,Pickleball,Rackets,Outdoor,Training,Sports,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/squash-racquets-pickleball-paddles-set-rackets/899913565.html?d1_page_num=1&dspm=pcen.sp.list.5.uQQD1pxO83xuKmCIH5t5&resource_id=899913565&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.&skuid=1159899760509198342#s1-4-1;searl|3159699503:5','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Squash Racquets Professional Pickleball Paddles Set of 2 Rackets with 4 Balls Carry Bag with Comfort Grip Wood for Indoor Outdoor Women Sports','price'=>81.50,'sku'=>'878990867','type'=>'Paddles','tags'=>'Squash,Racquets,Professional,Pickleball,Paddles,Set,of,2,Rackets,with,4,Balls,Carry,Bag,with,Comfort,Grip,Wood,for,Indoor,Outdoor,Women,Sports,Paddles','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/squash-racquets-professional-pickleball-paddles/878990867.html?d1_page_num=1&dspm=pcen.sp.list.3.uQQD1pxO83xuKmCIH5t5&resource_id=878990867&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-2-1;searl|3159699503:3','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Eco Walker Court Line Marker Set Create Your Own Mini Pickleball Tennis Court','price'=>90.63,'sku'=>'B09C81QZHF','type'=>'Court','tags'=>'Eco,Walker,Court,Line,Marker,Set,Create,Your,Own,Mini,Pickleball,Tennis,Court,Court','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com/dp/B09C81QZHF/ref=sspa_dk_detail_0?pd_rd_i=B09C81QZHF&pd_rd_w=q9anz&content-id=amzn1.sym.386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_p=386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_r=FMJPE62K77BHV7E4Z4CN&pd_rd_wg=C10L7&pd_rd_r=7544627c-36b0-4bc7-8d34-d5930f7ccfd9&s=sporting-goods&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExUzRZWjNIUTI2T1lRJmVuY3J5cHRlZElkPUEwMjI0MDg5RlAwQ0U3MVAxT1BNJmVuY3J5cHRlZEFkSWQ9QTA0ODE0NzQyTzRZRTJTWldITjZEJndpZGdldE5hbWU9c3BfZGV0YWlsX3RoZW1hdGljJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ&th=1','delivery'=>19]);
        DB::table('products')->insert(['name'=>'Quick Court Indoor Pickleball Court Marking Tape, The Complete Pickleball Court Marking Kit - 2 x 230FT, Pickleball Court Tape with Instructions Included for Fast Court Marking','price'=>57.21,'sku'=>'B09YPP2TGX','type'=>'Court','tags'=>'Quick,Court,Indoor,Pickleball,Court,Marking,Tape,,The,Complete,Pickleball,Court,Marking,Kit,-,2,x,230FT,,Pickleball,Court,Tape,with,Instructions,Included,for,Fast,Court,Marking,Court','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com/Quick-Court-Pickleball-Marking-Complete/dp/B09YPP2TGX/ref=sr_1_5?keywords=pickleball%2Btape&qid=1699422953&sr=8-5&th=1','delivery'=>15]);
        DB::table('products')->insert(['name'=>'HolderProf Sports Pickleball Court Tape, 2in x 230FT - Pickleball Tape for Indoor Outdoor Court Lines Marking Kit | Bright Yellow','price'=>67.62,'sku'=>'B0CBPK1TKG','type'=>'Court','tags'=>'HolderProf,Sports,Pickleball,Court,Tape,,2in,x,230FT,-,Pickleball,Tape,for,Indoor,Outdoor,Court,Lines,Marking,Kit,|,Bright,Yellow,Court','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com/HolderProf-Sports-Pickleball-Court-230FT/dp/B0CBPK1TKG/ref=sr_1_6?keywords=pickleball+tape&qid=1699422953&sr=8-6','delivery'=>15]);
        DB::table('products')->insert(['name'=>'Fostoy Pickleball Set with Net, 22 FT Pickleball Net Regulation Full Size, Portable Pickle Ball Game Net System for Driveway Backyards, with Weather Resistant Metal Frame, Strong PE Net, Carrying Bag','price'=>232.56,'sku'=>'‎B0C8J32B35','type'=>'Court','tags'=>'Fostoy,Pickleball,Set,with,Net,,22,FT,Pickleball,Net,Regulation,Full,Size,,Portable,Pickle,Ball,Game,Net,System,for,Driveway,Backyards,,with,Weather,Resistant,Metal,Frame,,Strong,PE,Net,,Carrying,Bag,Court','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com/Deeliva-Pickleball-Driveway-Portable-Resistant/dp/B0B7DQFK24/ref=sr_1_16?keywords=pickleball%2Bcourt&qid=1699423016&sr=8-16&th=1','delivery'=>15]);
        DB::table('products')->insert(['name'=>'Pickleball-X Quikset Starter Set - Official Starter Net of The US Open','price'=>228.15,'sku'=>'B0179MLE2Y','type'=>'Court','tags'=>'Pickleball-X,Quikset,Starter,Set,-,Official,Starter,Net,of,The,US,Open,Court','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/Franklin-Sports-Pickleball-Starter-Set/dp/B0179MLE2Y/ref=sr_1_30?crid=M8Z23V0ZURA9&keywords=pickleball+net&qid=1699424206&sprefix=pickleball+net%2Caps%2C564&sr=8-30','delivery'=>21]);
        DB::table('products')->insert(['name'=>'NQV Pickleball Set with Net,Pickleball Set,10FT Half Court Pickleball Net Portable Outdoor Indoor for Driveway Home, Pickleball Set with 4 Paddles and Net+4 Pickleballs+1 Storage Bag+2 Chalks, Black','price'=>267.45,'sku'=>'B0BV22ZMNB','type'=>'Court','tags'=>'NQV,Pickleball,Set,with,Net,Pickleball,Set,10FT,Half,Court,Pickleball,Net,Portable,Outdoor,Indoor,for,Driveway,Home,,Pickleball,Set,with,4,Paddles,and,Net+4,Pickleballs+1,Storage,Bag+2,Chalks,,Black,Court','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/NQV-Pickleball-Portable-Driveway-Pickleballs/dp/B0BV22ZMNB/ref=sr_1_11?crid=M8Z23V0ZURA9&keywords=pickleball+net&qid=1699424206&sprefix=pickleball+net%2Caps%2C564&sr=8-11','delivery'=>20]);
        DB::table('products')->insert(['name'=>'PICKLETECH 4.0 Slim Version Portable Pickleball Nets Outdoor Game 22 FT Pickleball Net-USAPA Regulation Size-Pickle Ball Net System with Carrying Bag for Driveway','price'=>368.92,'sku'=>'B0BX9JC3KT','type'=>'Court','tags'=>'PICKLETECH,4.0,Slim,Version,Portable,Pickleball,Nets,Outdoor,Game,22,FT,Pickleball,Net-USAPA,Regulation,Size-Pickle,Ball,Net,System,with,Carrying,Bag,for,Driveway,Court','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/PICKLETECH-Pickleball-Net-USAPA-Regulation-Size-Pickle/dp/B0BX9JC3KT/ref=sr_1_27?crid=M8Z23V0ZURA9&keywords=pickleball%2Bnet&qid=1699424206&sprefix=pickleball%2Bnet%2Caps%2C564&sr=8-27&th=1','delivery'=>20]);
        DB::table('products')->insert(['name'=>'Pickleball Balls 12 Pack Outdoor Indooor Pickleball Balls USAPA Pickleball Approved Official Sports Pickle Balls Pickleballs for Outdoor Play,40 Holes Pickleball with Net Bag,Neon Green','price'=>43.47,'sku'=>'B0BZ93FLV7','type'=>'Accessories','tags'=>'Pickleball,Balls,12,Pack,Outdoor,Indooor,Pickleball,Balls,USAPA,Pickleball,Approved,Official,Sports,Pickle,Balls,Pickleballs,for,Outdoor,Play,40,Holes,Pickleball,with,Net,Bag,Neon,Green,Accessories','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/Pickleball-Outdoor-Approved-Official-Pickleballs/dp/B0BZ93FLV7/ref=sr_1_5?crid=1JWCH2E6JHFQ8&keywords=pickleballs&qid=1699424910&sprefix=pickleballs%2Caps%2C548&sr=8-5','delivery'=>8]);
        DB::table('products')->insert(['name'=>'Franklin Sports X-26 Indoor Pickleballs - USAPA Approved','price'=>85.10,'sku'=>'B07Q23Q17V','type'=>'Accessories','tags'=>'Franklin,Sports,X-26,Indoor,Pickleballs,-,USAPA,Approved,Accessories','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/Franklin-Sports-X-26-Indoor-Pickleballs/dp/B07Q23Q17V/ref=sr_1_5?crid=3Q4B9KGMI6WCC&keywords=blue%2Bpickleballs&qid=1699425005&sprefix=blpickleballs%2Caps%2C258&sr=8-5&th=1','delivery'=>8]);
        DB::table('products')->insert(['name'=>'12 Packs 40 Holes Outdoor Pickleball Balls for Outdoor Courts','price'=>50.82,'sku'=>'B0BTDHRLCM','type'=>'Accessories','tags'=>'12,Packs,40,Holes,Outdoor,Pickleball,Balls,for,Outdoor,Courts,Accessories','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/Packs-Holes-Outdoor-Pickleball-Courts/dp/B0BTDHRLCM/ref=sr_1_6?crid=VCSQARIQMD9W&keywords=outdoor%2Bpickleballs&qid=1699425165&sprefix=outdoopickleballs%2Caps%2C309&sr=8-6&th=1','delivery'=>8]);
        DB::table('products')->insert(['name'=>'Compression Arthritis Gloves, Copper Fiber Relief Hand Arthritis Joint Pain Half&Full Finger Anti-Slip Sports Gloves for Men Women','price'=>34.50,'sku'=>' B08PKX82NC','type'=>'Accessories','tags'=>'Compression,Arthritis,Gloves,,Copper,Fiber,Relief,Hand,Arthritis,Joint,Pain,Half&Full,Finger,Anti-Slip,Sports,Gloves,for,Men,Women,Accessories','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/Compression-Arthritis-Gloves-Copper-Anti-Slip/dp/B08KZYMF7R/ref=sr_1_1_sspa?crid=CZKP3AP0DCXH&keywords=pickleball%2Bglove&qid=1699425655&sprefix=pickleball%2Bg%2Caps%2C227&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1','delivery'=>6]);
        DB::table('products')->insert(['name'=>'Tourna Sports Tennis and Pickleball Glove - Mens Half Finger','price'=>51.75,'sku'=>'B086WNBCZB','type'=>'Accessories','tags'=>'Tourna,Sports,Tennis,and,Pickleball,Glove,-,Mens,Half,Finger,Accessories','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/Tourna-TGH-M-L-R-Tennis-Glove-Mens-Finger-Large-Right/dp/B086WNBCZB/ref=sr_1_7?crid=CZKP3AP0DCXH&keywords=pickleball%2Bglove&qid=1699425655&sprefix=pickleball%2Bg%2Caps%2C227&sr=8-7&th=1','delivery'=>20]);
        DB::table('products')->insert(['name'=>'Cozi Winter Pickleball Gloves','price'=>149.81,'sku'=>'‎B0BWVD47KZ','type'=>'Accessories','tags'=>'Cozi,Winter,Pickleball,Gloves,Accessories','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.amazon.com.au/COZI-Winter-Pickleball-Gloves-Medium/dp/B0BWVC7TS7/ref=sr_1_6?crid=CZKP3AP0DCXH&keywords=pickleball+glove&qid=1699425655&sprefix=pickleball+g%2Caps%2C227&sr=8-6','delivery'=>20]);
        DB::table('products')->insert(['name'=>'Mens T-Shirts Mens Shorts Playing Pickleball Improves Memory Dink Player T Shirt for Men Cotton T-Shirts Crew Neck Tees Short Sleeve Clothing','price'=>37.50,'sku'=>'888632255','type'=>'Clothing','tags'=>'Mens,T-Shirts,Mens,Shorts,Playing,Pickleball,Improves,Memory,Dink,Player,T,Shirt,for,Men,Cotton,T-Shirts,Crew,Neck,Tees,Short,Sleeve,Clothing,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-t-shirts-men-s-shorts-playing-pickleball/888632255.html?d1_page_num=1&dspm=pcen.sp.list.5.smGFpSNzsN9pw9LD6187&resource_id=888632255&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-1-1;searl|2051079628:2','delivery'=>17]);
        DB::table('products')->insert(['name'=>'Mens Polos Funny Pickleball Tshirt Paddle Shirt T-Shirt Prevailing Men Tops Shirts Cool T Cotton Unique','price'=>52.50,'sku'=>'877910605','type'=>'Clothing','tags'=>'Mens,Polos,Funny,Pickleball,Tshirt,Paddle,Shirt,T-Shirt,Prevailing,Men,Tops,Shirts,Cool,T,Cotton,Unique,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-polos-funny-pickleball-tshirt-paddle/877910605.html?d1_page_num=1&dspm=pcen.sp.list.9.smGFpSNzsN9pw9LD6187&resource_id=877910605&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.&skuAttr=1007914:1419842#s1-5-1;searl|2051079628:6','delivery'=>14]);
        DB::table('products')->insert(['name'=>'Mens T Shirts Shirt 2023 Printed Men Humorous Pickle With Pickleball Paddle And Net Women T-Shirt','price'=>63.00,'sku'=>'856656069','type'=>'Clothing','tags'=>'Mens,T,Shirts,Shirt,2023,Printed,Men,Humorous,Pickle,With,Pickleball,Paddle,And,Net,Women,T-Shirt,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-t-shirts-shirt-2023-printed-men-humorous/856656069.html?d1_page_num=1&dspm=pcen.sp.list.7.smGFpSNzsN9pw9LD6187&resource_id=856656069&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.&skuid=1104424209453822141#s1-3-1;searl|2051079628:4','delivery'=>15]);
        DB::table('products')->insert(['name'=>'Mens T Shirts I Like Beer And Pickleball Maybe 3 People Shirt Summer Style Graphic Cotton Streetwear Short Sleeve Birthday Gifts T-shirt','price'=>37.50,'sku'=>'886143588','type'=>'Clothing','tags'=>'Mens,T,Shirts,I,Like,Beer,And,Pickleball,Maybe,3,People,Shirt,Summer,Style,Graphic,Cotton,Streetwear,Short,Sleeve,Birthday,Gifts,T-shirt,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-t-shirts-i-like-beer-and-pickleball/886143588.html?d1_page_num=1&dspm=pcen.sp.list.11.smGFpSNzsN9pw9LD6187&resource_id=886143588&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-7-1;searl|2051079628:8','delivery'=>16]);
        DB::table('products')->insert(['name'=>'Mens T Shirts Great Minds Dink Alike Pickleball Fashion Vintage Graphic Oversized Sleeve Streetwear Mens Clothes','price'=>45.00,'sku'=>'855829294','type'=>'Clothing','tags'=>'Mens,T,Shirts,Great,Minds,Dink,Alike,Pickleball,Fashion,Vintage,Graphic,Oversized,Sleeve,Streetwear,Mens,Clothes,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-t-shirts-great-minds-dink-alike-pickleball/855829294.html?d1_page_num=1&dspm=pcen.sp.list.22.3iOwGG52bklExZ14OuJV&resource_id=855829294&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-21-1;searl|3563158674:22','delivery'=>16]);
        DB::table('products')->insert(['name'=>'Womens Hoodies Funny Pickleball Hoodie Smile IconA Sweatshirts Y2k Clothes Unisex Mens Long Sleeve Casual Women Streetwear Kawaii Tops','price'=>60.00,'sku'=>'891858340','type'=>'Clothing','tags'=>'Womens,Hoodies,Funny,Pickleball,Hoodie,Smile,IconA,Sweatshirts,Y2k,Clothes,Unisex,Mens,Long,Sleeve,Casual,Women,Streetwear,Kawaii,Tops,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/women-s-hoodies-funny-pickleball-hoodie-smile/891858340.html?d1_page_num=1&dspm=pcen.sp.list.20.3iOwGG52bklExZ14OuJV&resource_id=891858340&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-19-1;searl|3563158674:20','delivery'=>16]);
        DB::table('products')->insert(['name'=>'Mens TShirts Vintage Dink Responsibly Funny Pickleball for Men Round Neck Cotton T Shirts Short Sleeve Tees Gift Idea Clothing','price'=>52.50,'sku'=>'856013840','type'=>'Clothing','tags'=>'Mens,TShirts,Vintage,Dink,Responsibly,Funny,Pickleball,for,Men,Round,Neck,Cotton,T,Shirts,Short,Sleeve,Tees,Gift,Idea,Clothing,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/mens-tshirts-vintage-dink-responsibly-funny/856013840.html?d1_page_num=1&dspm=pcen.sp.list.16.3iOwGG52bklExZ14OuJV&resource_id=856013840&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-15-1;searl|3563158674:16','delivery'=>22]);
        DB::table('products')->insert(['name'=>'Mens T Shirts You Are Got Another Dink Comin Pickleball Funny Kawaii Anime Christmas Oversized Mens Clothes','price'=>45.00,'sku'=>'855829245','type'=>'Clothing','tags'=>'Mens,T,Shirts,You,Are,Got,Another,Dink,Comin,Pickleball,Funny,Kawaii,Anime,Christmas,Oversized,Mens,Clothes,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-t-shirts-you-are-got-another-dink-comin/855829245.html?d1_page_num=1&dspm=pcen.sp.list.14.3iOwGG52bklExZ14OuJV&resource_id=855829245&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-13-1;searl|3563158674:14','delivery'=>16]);
        DB::table('products')->insert(['name'=>'Mens Tracksuits Obsessive Pickleball Disorder Tshirts Outfit Plus Size Slim Fit Men Tshirt Design Streetwear','price'=>45.00,'sku'=>'889313855','type'=>'Clothing','tags'=>'Mens,Tracksuits,Obsessive,Pickleball,Disorder,Tshirts,Outfit,Plus,Size,Slim,Fit,Men,Tshirt,Design,Streetwear,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-tracksuits-obsessive-pickleball-disorder/889313855.html?d1_page_num=1&dspm=pcen.sp.list.12.3iOwGG52bklExZ14OuJV&resource_id=889313855&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-11-1;searl|3563158674:12','delivery'=>16]);
        DB::table('products')->insert(['name'=>'Mens Tracksuits Obsessive Pickleball Disorder Tshirts Outfit Plus Size Slim Fit Men Shorts Design Streetwear','price'=>52.50,'sku'=>'889313856','type'=>'Clothing','tags'=>'Mens,Tracksuits,Obsessive,Pickleball,Disorder,Tshirts,Outfit,Plus,Size,Slim,Fit,Men,Tshirt,Design,Streetwear,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-tracksuits-obsessive-pickleball-disorder/889313855.html?d1_page_num=1&dspm=pcen.sp.list.12.3iOwGG52bklExZ14OuJV&resource_id=889313855&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-11-1;searl|3563158674:13','delivery'=>16]);
        DB::table('products')->insert(['name'=>'Mens Hoodies Why I Lose At Pickleball Humor Sports Pickleballers Gift Women Men Clothing Casual Y2k Unisex Soft Pullover Sweatshirt','price'=>60.00,'sku'=>'915210537','type'=>'Clothing','tags'=>'Mens,Hoodies,Why,I,Lose,At,Pickleball,Humor,Sports,Pickleballers,Gift,Women,Men,Clothing,Casual,Y2k,Unisex,Soft,Pullover,Sweatshirt,Clothing','description'=>'','rating'=>0,'available'=>true,'url'=>'https://www.dhgate.com/product/men-s-hoodies-why-i-lose-at-pickleball-humor/915210537.html?d1_page_num=1&dspm=pcen.sp.list.5.3iOwGG52bklExZ14OuJV&resource_id=915210537&scm_id=search.LIST..@.prerank001|3|0|fm2|7_0|ER-B|newes|7_0.newC.#s1-4-1;searl|3563158674:5','delivery'=>15]);

    }
}
